import { describe, expect, test } from 'vitest'

import {
  decodeVerificationURLHash,
  encodeVerificationURLHash,
} from './encode-url-hash'

describe('Encode URL hash', () => {
  test('should encode and decode verification hash', () => {
    const data = {
      signature:
        'k-n7d-9Pcx6ht87F4riP5xAw1v7S-e1HGMRaeaO068Q3IF1Jo8xOyeMT9Yr3Wv349Z2CdBzylw8M83CgQhcMogA=', // not generated by the pk
      publicKey: 'zQ3shUHp2rAM1yqBYeo6LhFbtrozG5mZeA6cRoGohsudtsieT',
    }

    const encodedHash = encodeVerificationURLHash(data)
    const decodedHash = decodeVerificationURLHash(encodedHash)

    expect(encodedHash).toBe(
      'Co0BClhrLW43ZC05UGN4Nmh0ODdGNHJpUDV4QXcxdjdTLWUxSEdNUmFlYU8wNjhRM0lGMUpvOHhPeWVNVDlZcjNXdjM0OVoyQ2RCenlsdzhNODNDZ1FoY01vZ0E9EjF6UTNzaFVIcDJyQU0xeXFCWWVvNkxoRmJ0cm96RzVtWmVBNmNSb0dvaHN1ZHRzaWVU'
    )
    expect(decodedHash).toEqual(data)
  })
})
