packages:
  - 'packages/eslint-config'
  - 'packages/status-js'
  - 'packages/colors'
  - 'packages/icons'
  - 'packages/components'
  - 'packages/wallet'
  - 'packages/trpc-webext'
  - 'apps/connector'
  - 'apps/portfolio'
  - 'apps/wallet'
  - 'apps/api'
