packages:
  - 'packages/eslint-config'
  - 'packages/status-js'
  - 'packages/colors'
  - 'packages/icons'
  - 'packages/components'
  - 'packages/status-network'
  - 'packages/wallet'
  - 'apps/hub'
  # - 'apps/status.app'
  # - 'apps/status.network'
  - 'apps/connector'
  - 'apps/portfolio'
  - 'apps/wallet'
  - 'apps/api'
