import { createTheme } from '@tamagui/core'

import { tokens } from './tokens'

const light = createTheme({
  primary: tokens.color['primary-50'],
  primaryHover: tokens.color['primary-60'],
  success: tokens.color['success-50'],
  successHover: tokens.color['success-60'],
  danger: tokens.color['danger-50'],
  dangerHover: tokens.color['danger-60'],
  purple: tokens.color['purple-50'],
  purpleHover: tokens.color['purple-60'],
  indigo: tokens.color['indigo-50'],
  indigoHover: tokens.color['indigo-60'],
  turquoise: tokens.color['turquoise-50'],
  turquoiseHover: tokens.color['turquoise-60'],
  blue: tokens.color['blue-50'],
  blueHover: tokens.color['blue-60'],
  green: tokens.color['green-50'],
  greenHover: tokens.color['green-60'],
  yellow: tokens.color['yellow-50'],
  yellowHover: tokens.color['yellow-60'],
  orange: tokens.color['orange-50'],
  orangeHover: tokens.color['orange-60'],
  red: tokens.color['red-50'],
  redHover: tokens.color['red-60'],
  pink: tokens.color['pink-50'],
  pinkHover: tokens.color['pink-60'],
  brown: tokens.color['brown-50'],
  brownHover: tokens.color['brown-60'],
  beige: tokens.color['beige-50'],
  beigeHover: tokens.color['beige-60'],
})

const dark = createTheme({
  primary: tokens.color['primary-60'],
  primaryHover: tokens.color['primary-50'],
  success: tokens.color['success-60'],
  successHover: tokens.color['success-50'],
  danger: tokens.color['danger-60'],
  dangerHover: tokens.color['danger-50'],
  purple: tokens.color['purple-60'],
  purpleHover: tokens.color['purple-50'],
  indigo: tokens.color['indigo-60'],
  indigoHover: tokens.color['indigo-50'],
  turquoise: tokens.color['turquoise-60'],
  turquoiseHover: tokens.color['turquoise-50'],
  blue: tokens.color['blue-60'],
  blueHover: tokens.color['blue-50'],
  green: tokens.color['green-60'],
  greenHover: tokens.color['green-50'],
  yellow: tokens.color['yellow-60'],
  yellowHover: tokens.color['yellow-50'],
  orange: tokens.color['orange-60'],
  orangeHover: tokens.color['orange-50'],
  red: tokens.color['red-60'],
  redHover: tokens.color['red-50'],
  pink: tokens.color['pink-60'],
  pinkHover: tokens.color['pink-50'],
  brown: tokens.color['brown-60'],
  brownHover: tokens.color['brown-50'],
  beige: tokens.color['beige-60'],
  beigeHover: tokens.color['beige-50'],
})

export const themes = {
  light,
  dark,
}
