export type { CommunityProps } from './routes'
export { Community } from './routes'
export { darkTheme, theme as lightTheme } from './styles/config'
export type { Config } from './types/config'
export { HashRouter, MemoryRouter } from 'react-router-dom'
