import {
  createAppJSONLD,
  JSONLDScript as BaseJSONLDScript,
} from '@status-im/components'

import type {
  ArticleSchema,
  BreadcrumbListSchema,
  JSONLDSchema,
  OrganizationSchema,
  SoftwareApplicationSchema,
  WebSiteSchema,
} from '@status-im/components'

/**
 * JSON-LD schema generators
 *
 * Note: All schemas generated by createAppJSONLD automatically include:
 * - "@context": "https://schema.org"
 * - "@type": based on the schema type (Organization, WebSite, BreadcrumbList, etc.)
 * - ListItem schemas in BreadcrumbList automatically include "@type": "ListItem"
 * - Support for @id, publisher, webpage, and softwareApplication
 * - All values must be provided explicitly - no defaults
 */
export const jsonLD = createAppJSONLD()

/**
 * Re-export types for convenience
 */
export type {
  ArticleSchema,
  BreadcrumbListSchema,
  JSONLDSchema,
  OrganizationSchema,
  SoftwareApplicationSchema,
  WebSiteSchema,
}

/**
 * Re-export JSONLDScript component
 */
export { BaseJSONLDScript as JSONLDScript }
