import {
  createAppJSONLD,
  JSONLDScript as BaseJSONLDScript,
} from '@status-im/components'

import type {
  ArticleSchema,
  BreadcrumbListSchema,
  JSONLDSchema,
  OrganizationSchema,
  SoftwareApplicationSchema,
  WebSiteSchema,
} from '@status-im/components'

/**
 * Status Hub social media links and related URLs
 */
const STATUS_HUB_SOCIAL_LINKS: string[] = [
  'https://status.network/',
  'https://x.com/StatusL2',
  'https://github.com/status-im',
]

/**
 * JSON-LD schema generators with Status Hub defaults
 *
 * Note: All schemas generated by createAppJSONLD automatically include:
 * - "@context": "https://schema.org"
 * - "@type": based on the schema type (Organization, WebSite, BreadcrumbList, etc.)
 * - ListItem schemas in BreadcrumbList automatically include "@type": "ListItem"
 * - Support for @id, publisher, webpage, and softwareApplication
 */
export const jsonLD = createAppJSONLD({
  defaultSiteUrl: 'https://hub.status.network',
  defaultSocialLinks: STATUS_HUB_SOCIAL_LINKS,
  defaultName: 'Status Network Hub',
  defaultUrl: 'https://hub.status.network',
})

/**
 * Re-export types for convenience
 */
export type {
  ArticleSchema,
  BreadcrumbListSchema,
  JSONLDSchema,
  OrganizationSchema,
  SoftwareApplicationSchema,
  WebSiteSchema,
}

/**
 * Re-export JSONLDScript component
 */
export { BaseJSONLDScript as JSONLDScript }
