import {
  createJSONLD,
  JSONLDScript as BaseJSONLDScript,
} from '@status-im/components'

import type {
  ArticleSchema,
  BreadcrumbListSchema,
  JSONLDSchema,
  OrganizationSchema,
  WebSiteSchema,
} from '@status-im/components'

const DEFAULT_NAME = 'Status Network Hub'
const DEFAULT_URL = 'https://hub.status.network'

/**
 * Status Hub social media links and related URLs
 */
const STATUS_HUB_SOCIAL_LINKS: string[] = [
  'https://status.network/',
  'https://x.com/StatusL2',
  'https://github.com/status-im',
]

/**
 * Create JSON-LD schema generators with Status Hub defaults
 *
 * Note: All schemas generated by createJSONLD automatically include:
 * - "@context": "https://schema.org"
 * - "@type": based on the schema type (Organization, WebSite, BreadcrumbList, etc.)
 * - ListItem schemas in BreadcrumbList automatically include "@type": "ListItem"
 */
const baseJsonLD = createJSONLD({
  defaultSiteUrl: DEFAULT_URL,
  defaultSocialLinks: STATUS_HUB_SOCIAL_LINKS,
})

type SoftwareApplicationSchema = {
  '@context': 'https://schema.org'
  '@type': 'SoftwareApplication'
  name: string
  applicationCategory: string
  operatingSystem: string
  url: string
  description?: string
}

/**
 * JSON-LD schema generators with app-specific defaults
 *
 * All schemas automatically include:
 * - "@context": "https://schema.org"
 * - "@type": "Organization" | "WebSite" | "BreadcrumbList" | "ListItem" | "SoftwareApplication" | etc.
 */
export const jsonLD = {
  ...baseJsonLD,
  organization: (config?: {
    '@id'?: string
    name?: string
    url?: string
    description?: string
    logo?: string
    sameAs?: string[]
  }) =>
    baseJsonLD.organization({
      name: config?.name ?? DEFAULT_NAME,
      url: config?.url ?? DEFAULT_URL,
      ...config,
    }),
  website: (config?: {
    '@id'?: string
    description?: string
    searchUrl?: string
    name?: string
    url?: string
    publisher?: {
      '@id'?: string
    }
  }) =>
    baseJsonLD.website({
      name: config?.name ?? DEFAULT_NAME,
      url: config?.url ?? DEFAULT_URL,
      description: config?.description,
      searchUrl: config?.searchUrl,
    }),
  softwareApplication: (config: {
    name: string
    applicationCategory: string
    operatingSystem: string
    url: string
    description?: string
  }): SoftwareApplicationSchema => ({
    '@context': 'https://schema.org',
    '@type': 'SoftwareApplication',
    name: config.name,
    applicationCategory: config.applicationCategory,
    operatingSystem: config.operatingSystem,
    url: config.url,
    ...(config.description && { description: config.description }),
  }),
}

/**
 * Re-export types for convenience
 */
export type {
  ArticleSchema,
  BreadcrumbListSchema,
  JSONLDSchema,
  OrganizationSchema,
  WebSiteSchema,
}

/**
 * Re-export JSONLDScript component
 */
export { BaseJSONLDScript as JSONLDScript }
