export { ComparisionSection } from './comparision-section'
export { HandsSection } from './hands-section'
export { HeroSection } from './hero-section'
export { ParalaxCircle } from './parallax-circle'
export { VideoSection } from './video-section'
