// @generated by protoc-gen-es v2.10.0 with parameter "target=ts"
// @generated from file membership-update-message.proto (syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from '@bufbuild/protobuf/codegenv2'
import { enumDesc, fileDesc, messageDesc } from '@bufbuild/protobuf/codegenv2'
import type { ChatMessage } from './chat-message_pb'
import { file_chat_message } from './chat-message_pb'
import type { EmojiReaction } from './emoji-reaction_pb'
import { file_emoji_reaction } from './emoji-reaction_pb'
import type { Message } from '@bufbuild/protobuf'

/**
 * Describes the file membership-update-message.proto.
 */
export const file_membership_update_message: GenFile =
  /*@__PURE__*/
  fileDesc(
    'Ch9tZW1iZXJzaGlwLXVwZGF0ZS1tZXNzYWdlLnByb3RvItcCChVNZW1iZXJzaGlwVXBkYXRlRXZlbnQSDQoFY2xvY2sYASABKAQSDwoHbWVtYmVycxgCIAMoCRIMCgRuYW1lGAMgASgJEi4KBHR5cGUYBCABKA4yIC5NZW1iZXJzaGlwVXBkYXRlRXZlbnQuRXZlbnRUeXBlEg0KBWNvbG9yGAUgASgJEg0KBWltYWdlGAYgASgMIsEBCglFdmVudFR5cGUSCwoHVU5LTk9XThAAEhAKDENIQVRfQ1JFQVRFRBABEhAKDE5BTUVfQ0hBTkdFRBACEhEKDU1FTUJFUlNfQURERUQQAxIRCg1NRU1CRVJfSk9JTkVEEAQSEgoOTUVNQkVSX1JFTU9WRUQQBRIQCgxBRE1JTlNfQURERUQQBhIRCg1BRE1JTl9SRU1PVkVEEAcSEQoNQ09MT1JfQ0hBTkdFRBAIEhEKDUlNQUdFX0NIQU5HRUQQCSKUAQoXTWVtYmVyc2hpcFVwZGF0ZU1lc3NhZ2USDwoHY2hhdF9pZBgBIAEoCRIOCgZldmVudHMYAiADKAwSHwoHbWVzc2FnZRgDIAEoCzIMLkNoYXRNZXNzYWdlSAASKAoOZW1vamlfcmVhY3Rpb24YBCABKAsyDi5FbW9qaVJlYWN0aW9uSABCDQoLY2hhdF9lbnRpdHliBnByb3RvMw',
    [file_chat_message, file_emoji_reaction],
  )

/**
 * @generated from message MembershipUpdateEvent
 */
export type MembershipUpdateEvent = Message<'MembershipUpdateEvent'> & {
  /**
   * Lamport timestamp of the event
   *
   * @generated from field: uint64 clock = 1;
   */
  clock: bigint

  /**
   * List of public keys of objects of the action
   *
   * @generated from field: repeated string members = 2;
   */
  members: string[]

  /**
   * Name of the chat for the CHAT_CREATED/NAME_CHANGED event types
   *
   * @generated from field: string name = 3;
   */
  name: string

  /**
   * The type of the event
   *
   * @generated from field: MembershipUpdateEvent.EventType type = 4;
   */
  type: MembershipUpdateEvent_EventType

  /**
   * Color of the chat for the CHAT_CREATED/COLOR_CHANGED event types
   *
   * @generated from field: string color = 5;
   */
  color: string

  /**
   * Chat image
   *
   * @generated from field: bytes image = 6;
   */
  image: Uint8Array
}

/**
 * Describes the message MembershipUpdateEvent.
 * Use `create(MembershipUpdateEventSchema)` to create a new message.
 */
export const MembershipUpdateEventSchema: GenMessage<MembershipUpdateEvent> =
  /*@__PURE__*/
  messageDesc(file_membership_update_message, 0)

/**
 * @generated from enum MembershipUpdateEvent.EventType
 */
export enum MembershipUpdateEvent_EventType {
  /**
   * @generated from enum value: UNKNOWN = 0;
   */
  UNKNOWN = 0,

  /**
   * @generated from enum value: CHAT_CREATED = 1;
   */
  CHAT_CREATED = 1,

  /**
   * @generated from enum value: NAME_CHANGED = 2;
   */
  NAME_CHANGED = 2,

  /**
   * @generated from enum value: MEMBERS_ADDED = 3;
   */
  MEMBERS_ADDED = 3,

  /**
   * @generated from enum value: MEMBER_JOINED = 4;
   */
  MEMBER_JOINED = 4,

  /**
   * @generated from enum value: MEMBER_REMOVED = 5;
   */
  MEMBER_REMOVED = 5,

  /**
   * @generated from enum value: ADMINS_ADDED = 6;
   */
  ADMINS_ADDED = 6,

  /**
   * @generated from enum value: ADMIN_REMOVED = 7;
   */
  ADMIN_REMOVED = 7,

  /**
   * @generated from enum value: COLOR_CHANGED = 8;
   */
  COLOR_CHANGED = 8,

  /**
   * @generated from enum value: IMAGE_CHANGED = 9;
   */
  IMAGE_CHANGED = 9,
}

/**
 * Describes the enum MembershipUpdateEvent.EventType.
 */
export const MembershipUpdateEvent_EventTypeSchema: GenEnum<MembershipUpdateEvent_EventType> =
  /*@__PURE__*/
  enumDesc(file_membership_update_message, 0, 0)

/**
 * MembershipUpdateMessage is a message used to propagate information
 * about group membership changes.
 * For more information, see https://github.com/status-im/specs/blob/master/status-group-chats-spec.md.
 *
 * @generated from message MembershipUpdateMessage
 */
export type MembershipUpdateMessage = Message<'MembershipUpdateMessage'> & {
  /**
   * The chat id of the private group chat
   *
   * @generated from field: string chat_id = 1;
   */
  chatId: string

  /**
   * A list of events for this group chat, first x bytes are the signature, then is a
   * protobuf encoded MembershipUpdateEvent
   *
   * @generated from field: repeated bytes events = 2;
   */
  events: Uint8Array[]

  /**
   * An optional chat message
   *
   * @generated from oneof MembershipUpdateMessage.chat_entity
   */
  chatEntity:
    | {
        /**
         * @generated from field: ChatMessage message = 3;
         */
        value: ChatMessage
        case: 'message'
      }
    | {
        /**
         * @generated from field: EmojiReaction emoji_reaction = 4;
         */
        value: EmojiReaction
        case: 'emojiReaction'
      }
    | { case: undefined; value?: undefined }
}

/**
 * Describes the message MembershipUpdateMessage.
 * Use `create(MembershipUpdateMessageSchema)` to create a new message.
 */
export const MembershipUpdateMessageSchema: GenMessage<MembershipUpdateMessage> =
  /*@__PURE__*/
  messageDesc(file_membership_update_message, 1)
