// @generated by protoc-gen-es v2.10.0 with parameter "target=ts"
// @generated from file status-update.proto (syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from '@bufbuild/protobuf/codegenv2'
import { enumDesc, fileDesc, messageDesc } from '@bufbuild/protobuf/codegenv2'
import type { Message } from '@bufbuild/protobuf'

/**
 * Describes the file status-update.proto.
 */
export const file_status_update: GenFile =
  /*@__PURE__*/
  fileDesc(
    'ChNzdGF0dXMtdXBkYXRlLnByb3RvIswBCgxTdGF0dXNVcGRhdGUSDQoFY2xvY2sYASABKAQSLQoLc3RhdHVzX3R5cGUYAiABKA4yGC5TdGF0dXNVcGRhdGUuU3RhdHVzVHlwZRITCgtjdXN0b21fdGV4dBgDIAEoCSJpCgpTdGF0dXNUeXBlEhcKE1VOS05PV05fU1RBVFVTX1RZUEUQABINCglBVVRPTUFUSUMQARISCg5ET19OT1RfRElTVFVSQhACEhEKDUFMV0FZU19PTkxJTkUQAxIMCghJTkFDVElWRRAEYgZwcm90bzM',
  )

/**
 * Specs:
 * :AUTOMATIC
 * To Send - "AUTOMATIC" status ping every 5 minutes
 * Display - Online for up to 5 minutes from the last clock, after that Offline
 * :ALWAYS_ONLINE
 * To Send - "ALWAYS_ONLINE" status ping every 5 minutes
 * Display - Online for up to 2 weeks from the last clock, after that Offline
 * :INACTIVE
 * To Send - A single "INACTIVE" status ping
 * Display - Offline forever
 * Note: Only send pings if the user interacted with the app in the last x minutes.
 *
 * @generated from message StatusUpdate
 */
export type StatusUpdate = Message<'StatusUpdate'> & {
  /**
   * @generated from field: uint64 clock = 1;
   */
  clock: bigint

  /**
   * @generated from field: StatusUpdate.StatusType status_type = 2;
   */
  statusType: StatusUpdate_StatusType

  /**
   * @generated from field: string custom_text = 3;
   */
  customText: string
}

/**
 * Describes the message StatusUpdate.
 * Use `create(StatusUpdateSchema)` to create a new message.
 */
export const StatusUpdateSchema: GenMessage<StatusUpdate> =
  /*@__PURE__*/
  messageDesc(file_status_update, 0)

/**
 * @generated from enum StatusUpdate.StatusType
 */
export enum StatusUpdate_StatusType {
  /**
   * @generated from enum value: UNKNOWN_STATUS_TYPE = 0;
   */
  UNKNOWN_STATUS_TYPE = 0,

  /**
   * @generated from enum value: AUTOMATIC = 1;
   */
  AUTOMATIC = 1,

  /**
   * @generated from enum value: DO_NOT_DISTURB = 2;
   */
  DO_NOT_DISTURB = 2,

  /**
   * @generated from enum value: ALWAYS_ONLINE = 3;
   */
  ALWAYS_ONLINE = 3,

  /**
   * @generated from enum value: INACTIVE = 4;
   */
  INACTIVE = 4,
}

/**
 * Describes the enum StatusUpdate.StatusType.
 */
export const StatusUpdate_StatusTypeSchema: GenEnum<StatusUpdate_StatusType> =
  /*@__PURE__*/
  enumDesc(file_status_update, 0, 0)
