export const vaultAbi = [
  {
    type: 'constructor',
    inputs: [
      { name: 'token', type: 'address', internalType: 'contract IERC20' },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'STAKING_TOKEN',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'contract IERC20' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'amountStaked',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'availableWithdraw',
    inputs: [
      { name: '_token', type: 'address', internalType: 'contract IERC20' },
    ],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'emergencyExit',
    inputs: [
      { name: '_destination', type: 'address', internalType: 'address' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'initialize',
    inputs: [
      { name: '_owner', type: 'address', internalType: 'address' },
      { name: '_stakeManager', type: 'address', internalType: 'address' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'leave',
    inputs: [
      { name: '_destination', type: 'address', internalType: 'address' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'lock',
    inputs: [{ name: '_seconds', type: 'uint256', internalType: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'migrateToVault',
    inputs: [{ name: 'migrateTo', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'owner',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'register',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'renounceOwnership',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'stake',
    inputs: [
      { name: '_amount', type: 'uint256', internalType: 'uint256' },
      { name: '_seconds', type: 'uint256', internalType: 'uint256' },
      { name: '_from', type: 'address', internalType: 'address' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'stake',
    inputs: [
      { name: '_amount', type: 'uint256', internalType: 'uint256' },
      { name: '_seconds', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'stakeManager',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'address',
        internalType: 'contract IStakeManagerProxy',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'stakeManagerImplementationAddress',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'transferOwnership',
    inputs: [{ name: 'newOwner', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'trustStakeManager',
    inputs: [
      { name: 'stakeManagerAddress', type: 'address', internalType: 'address' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'unstake',
    inputs: [{ name: '_amount', type: 'uint256', internalType: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'unstake',
    inputs: [
      { name: '_amount', type: 'uint256', internalType: 'uint256' },
      { name: '_destination', type: 'address', internalType: 'address' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'withdraw',
    inputs: [
      { name: '_token', type: 'address', internalType: 'contract IERC20' },
      { name: '_amount', type: 'uint256', internalType: 'uint256' },
      { name: '_destination', type: 'address', internalType: 'address' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'withdraw',
    inputs: [
      { name: '_token', type: 'address', internalType: 'contract IERC20' },
      { name: '_amount', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'event',
    name: 'Initialized',
    inputs: [
      { name: 'version', type: 'uint8', indexed: false, internalType: 'uint8' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'OwnershipTransferred',
    inputs: [
      {
        name: 'previousOwner',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'newOwner',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
    ],
    anonymous: false,
  },
  { type: 'error', name: 'StakeVault__InvalidDestinationAddress', inputs: [] },
  { type: 'error', name: 'StakeVault__MigrationFailed', inputs: [] },
  { type: 'error', name: 'StakeVault__NotAllowedToExit', inputs: [] },
  { type: 'error', name: 'StakeVault__NotAllowedToLeave', inputs: [] },
  { type: 'error', name: 'StakeVault__NotEnoughAvailableBalance', inputs: [] },
  {
    type: 'error',
    name: 'StakeVault__StakeManagerImplementationNotTrusted',
    inputs: [],
  },
  { type: 'error', name: 'StakeVault__StakingFailed', inputs: [] },
  { type: 'error', name: 'StakeVault__UnstakingFailed', inputs: [] },
] as const
