/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as OnboardingLayoutImport } from './routes/onboarding/_layout'
import { Route as IndexImport } from './routes/index'
import { Route as PortfolioIndexImport } from './routes/portfolio/index'
import { Route as OnboardingIndexImport } from './routes/onboarding/index'
import { Route as OnboardingNewImport } from './routes/onboarding/new'
import { Route as OnboardingImportImport } from './routes/onboarding/import'

// Create/Update Routes

const OnboardingLayoutRoute = OnboardingLayoutImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PortfolioIndexRoute = PortfolioIndexImport.update({
  id: '/portfolio/',
  path: '/portfolio/',
  getParentRoute: () => rootRoute,
} as any)

const OnboardingIndexRoute = OnboardingIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingLayoutRoute,
} as any)

const OnboardingNewRoute = OnboardingNewImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => OnboardingLayoutRoute,
} as any)

const OnboardingImportRoute = OnboardingImportImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => OnboardingLayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingLayoutImport
      parentRoute: typeof rootRoute
    }
    '/onboarding/import': {
      id: '/onboarding/import'
      path: '/import'
      fullPath: '/onboarding/import'
      preLoaderRoute: typeof OnboardingImportImport
      parentRoute: typeof OnboardingLayoutImport
    }
    '/onboarding/new': {
      id: '/onboarding/new'
      path: '/new'
      fullPath: '/onboarding/new'
      preLoaderRoute: typeof OnboardingNewImport
      parentRoute: typeof OnboardingLayoutImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexImport
      parentRoute: typeof OnboardingLayoutImport
    }
    '/portfolio/': {
      id: '/portfolio/'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface OnboardingLayoutRouteChildren {
  OnboardingImportRoute: typeof OnboardingImportRoute
  OnboardingNewRoute: typeof OnboardingNewRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingLayoutRouteChildren: OnboardingLayoutRouteChildren = {
  OnboardingImportRoute: OnboardingImportRoute,
  OnboardingNewRoute: OnboardingNewRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingLayoutRouteWithChildren =
  OnboardingLayoutRoute._addFileChildren(OnboardingLayoutRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingLayoutRouteWithChildren
  '/onboarding/import': typeof OnboardingImportRoute
  '/onboarding/new': typeof OnboardingNewRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/portfolio': typeof PortfolioIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding/import': typeof OnboardingImportRoute
  '/onboarding/new': typeof OnboardingNewRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/portfolio': typeof PortfolioIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingLayoutRouteWithChildren
  '/onboarding/import': typeof OnboardingImportRoute
  '/onboarding/new': typeof OnboardingNewRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/onboarding/import'
    | '/onboarding/new'
    | '/onboarding/'
    | '/portfolio'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding/import'
    | '/onboarding/new'
    | '/onboarding'
    | '/portfolio'
  id:
    | '__root__'
    | '/'
    | '/onboarding'
    | '/onboarding/import'
    | '/onboarding/new'
    | '/onboarding/'
    | '/portfolio/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OnboardingLayoutRoute: typeof OnboardingLayoutRouteWithChildren
  PortfolioIndexRoute: typeof PortfolioIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OnboardingLayoutRoute: OnboardingLayoutRouteWithChildren,
  PortfolioIndexRoute: PortfolioIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/onboarding",
        "/portfolio/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/onboarding": {
      "filePath": "onboarding/_layout.tsx",
      "children": [
        "/onboarding/import",
        "/onboarding/new",
        "/onboarding/"
      ]
    },
    "/onboarding/import": {
      "filePath": "onboarding/import.tsx",
      "parent": "/onboarding"
    },
    "/onboarding/new": {
      "filePath": "onboarding/new.tsx",
      "parent": "/onboarding"
    },
    "/onboarding/": {
      "filePath": "onboarding/index.tsx",
      "parent": "/onboarding"
    },
    "/portfolio/": {
      "filePath": "portfolio/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
