/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingLayoutRouteImport } from './routes/onboarding/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as OnboardingNewRouteImport } from './routes/onboarding/new'
import { Route as OnboardingImportRouteImport } from './routes/onboarding/import'
import { Route as PortfolioCollectiblesIndexRouteImport } from './routes/portfolio/collectibles/index'
import { Route as PortfolioAssetsIndexRouteImport } from './routes/portfolio/assets/index'
import { Route as PortfolioActivityIndexRouteImport } from './routes/portfolio/activity/index'
import { Route as PortfolioAssetsTickerRouteImport } from './routes/portfolio/assets/$ticker'
import { Route as PortfolioCollectiblesNetworkContractIdRouteImport } from './routes/portfolio/collectibles/$network/$contract/$id'

const OnboardingLayoutRoute = OnboardingLayoutRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingLayoutRoute,
} as any)
const OnboardingNewRoute = OnboardingNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => OnboardingLayoutRoute,
} as any)
const OnboardingImportRoute = OnboardingImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => OnboardingLayoutRoute,
} as any)
const PortfolioCollectiblesIndexRoute =
  PortfolioCollectiblesIndexRouteImport.update({
    id: '/portfolio/collectibles/',
    path: '/portfolio/collectibles/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PortfolioAssetsIndexRoute = PortfolioAssetsIndexRouteImport.update({
  id: '/portfolio/assets/',
  path: '/portfolio/assets/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioActivityIndexRoute = PortfolioActivityIndexRouteImport.update({
  id: '/portfolio/activity/',
  path: '/portfolio/activity/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioAssetsTickerRoute = PortfolioAssetsTickerRouteImport.update({
  id: '/portfolio/assets/$ticker',
  path: '/portfolio/assets/$ticker',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioCollectiblesNetworkContractIdRoute =
  PortfolioCollectiblesNetworkContractIdRouteImport.update({
    id: '/portfolio/collectibles/$network/$contract/$id',
    path: '/portfolio/collectibles/$network/$contract/$id',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingLayoutRouteWithChildren
  '/onboarding/import': typeof OnboardingImportRoute
  '/onboarding/new': typeof OnboardingNewRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/portfolio/assets/$ticker': typeof PortfolioAssetsTickerRoute
  '/portfolio/activity': typeof PortfolioActivityIndexRoute
  '/portfolio/assets': typeof PortfolioAssetsIndexRoute
  '/portfolio/collectibles': typeof PortfolioCollectiblesIndexRoute
  '/portfolio/collectibles/$network/$contract/$id': typeof PortfolioCollectiblesNetworkContractIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding/import': typeof OnboardingImportRoute
  '/onboarding/new': typeof OnboardingNewRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/portfolio/assets/$ticker': typeof PortfolioAssetsTickerRoute
  '/portfolio/activity': typeof PortfolioActivityIndexRoute
  '/portfolio/assets': typeof PortfolioAssetsIndexRoute
  '/portfolio/collectibles': typeof PortfolioCollectiblesIndexRoute
  '/portfolio/collectibles/$network/$contract/$id': typeof PortfolioCollectiblesNetworkContractIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingLayoutRouteWithChildren
  '/onboarding/import': typeof OnboardingImportRoute
  '/onboarding/new': typeof OnboardingNewRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/portfolio/assets/$ticker': typeof PortfolioAssetsTickerRoute
  '/portfolio/activity/': typeof PortfolioActivityIndexRoute
  '/portfolio/assets/': typeof PortfolioAssetsIndexRoute
  '/portfolio/collectibles/': typeof PortfolioCollectiblesIndexRoute
  '/portfolio/collectibles/$network/$contract/$id': typeof PortfolioCollectiblesNetworkContractIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/onboarding/import'
    | '/onboarding/new'
    | '/onboarding/'
    | '/portfolio/assets/$ticker'
    | '/portfolio/activity'
    | '/portfolio/assets'
    | '/portfolio/collectibles'
    | '/portfolio/collectibles/$network/$contract/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding/import'
    | '/onboarding/new'
    | '/onboarding'
    | '/portfolio/assets/$ticker'
    | '/portfolio/activity'
    | '/portfolio/assets'
    | '/portfolio/collectibles'
    | '/portfolio/collectibles/$network/$contract/$id'
  id:
    | '__root__'
    | '/'
    | '/onboarding'
    | '/onboarding/import'
    | '/onboarding/new'
    | '/onboarding/'
    | '/portfolio/assets/$ticker'
    | '/portfolio/activity/'
    | '/portfolio/assets/'
    | '/portfolio/collectibles/'
    | '/portfolio/collectibles/$network/$contract/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OnboardingLayoutRoute: typeof OnboardingLayoutRouteWithChildren
  PortfolioAssetsTickerRoute: typeof PortfolioAssetsTickerRoute
  PortfolioActivityIndexRoute: typeof PortfolioActivityIndexRoute
  PortfolioAssetsIndexRoute: typeof PortfolioAssetsIndexRoute
  PortfolioCollectiblesIndexRoute: typeof PortfolioCollectiblesIndexRoute
  PortfolioCollectiblesNetworkContractIdRoute: typeof PortfolioCollectiblesNetworkContractIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingLayoutRoute
    }
    '/onboarding/new': {
      id: '/onboarding/new'
      path: '/new'
      fullPath: '/onboarding/new'
      preLoaderRoute: typeof OnboardingNewRouteImport
      parentRoute: typeof OnboardingLayoutRoute
    }
    '/onboarding/import': {
      id: '/onboarding/import'
      path: '/import'
      fullPath: '/onboarding/import'
      preLoaderRoute: typeof OnboardingImportRouteImport
      parentRoute: typeof OnboardingLayoutRoute
    }
    '/portfolio/collectibles/': {
      id: '/portfolio/collectibles/'
      path: '/portfolio/collectibles'
      fullPath: '/portfolio/collectibles'
      preLoaderRoute: typeof PortfolioCollectiblesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/assets/': {
      id: '/portfolio/assets/'
      path: '/portfolio/assets'
      fullPath: '/portfolio/assets'
      preLoaderRoute: typeof PortfolioAssetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/activity/': {
      id: '/portfolio/activity/'
      path: '/portfolio/activity'
      fullPath: '/portfolio/activity'
      preLoaderRoute: typeof PortfolioActivityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/assets/$ticker': {
      id: '/portfolio/assets/$ticker'
      path: '/portfolio/assets/$ticker'
      fullPath: '/portfolio/assets/$ticker'
      preLoaderRoute: typeof PortfolioAssetsTickerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/collectibles/$network/$contract/$id': {
      id: '/portfolio/collectibles/$network/$contract/$id'
      path: '/portfolio/collectibles/$network/$contract/$id'
      fullPath: '/portfolio/collectibles/$network/$contract/$id'
      preLoaderRoute: typeof PortfolioCollectiblesNetworkContractIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OnboardingLayoutRouteChildren {
  OnboardingImportRoute: typeof OnboardingImportRoute
  OnboardingNewRoute: typeof OnboardingNewRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingLayoutRouteChildren: OnboardingLayoutRouteChildren = {
  OnboardingImportRoute: OnboardingImportRoute,
  OnboardingNewRoute: OnboardingNewRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingLayoutRouteWithChildren =
  OnboardingLayoutRoute._addFileChildren(OnboardingLayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OnboardingLayoutRoute: OnboardingLayoutRouteWithChildren,
  PortfolioAssetsTickerRoute: PortfolioAssetsTickerRoute,
  PortfolioActivityIndexRoute: PortfolioActivityIndexRoute,
  PortfolioAssetsIndexRoute: PortfolioAssetsIndexRoute,
  PortfolioCollectiblesIndexRoute: PortfolioCollectiblesIndexRoute,
  PortfolioCollectiblesNetworkContractIdRoute:
    PortfolioCollectiblesNetworkContractIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
