#!/usr/bin/env bash
# Vercel build for @status-im/community-dapp.
# Runs from the app dir (vercel root directory = apps/community-dapp).
set -euo pipefail

# Contract ABIs are generated by `forge build` and gitignored, so they must be
# built here. Fetch the contracts' submodules and install Foundry first.
git -C ../../ submodule update --init --recursive packages/community-contracts/lib
curl -L https://foundry.paradigm.xyz | bash
export PATH="$HOME/.foundry/bin:$PATH"
foundryup

pnpm --filter @status-im/community-contracts run build
pnpm --filter @status-im/js run build
pnpm --filter @status-im/community-dapp run generate:proto

NODE_OPTIONS=--openssl-legacy-provider pnpm exec webpack --mode=production
