#!/usr/bin/env bash
# Vercel build for @status-im/community-dapp.
# Runs from the app dir (vercel root directory = apps/community-dapp).
set -euo pipefail

# Kept in sync with the foundry-toolchain version in .github/workflows/ci.yml.
FOUNDRY_VERSION=v1.5.1

# Contract ABIs are generated by `forge build` and gitignored, so they must be
# built here. Fetch the contracts' submodules and install Foundry first.
git -C ../../ submodule update --init --recursive packages/community-contracts/lib
curl -L https://foundry.paradigm.xyz | bash
export PATH="$HOME/.foundry/bin:$PATH"
# --force skips foundryup's attestation check, which reads the manifest through
# bash process substitution. Vercel's build container has no /dev/fd, so that
# redirection fails and aborts the install.
foundryup --install "$FOUNDRY_VERSION" --force

pnpm --filter @status-im/community-contracts run build
pnpm --filter @status-im/js run build
pnpm --filter @status-im/community-dapp run generate:proto

NODE_OPTIONS=--openssl-legacy-provider pnpm exec webpack --mode=production
